last spl2/ASPSWebApp/Controllers/CourseRecommendationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASPSDAL;

namespace ASPSWebApp.Controllers
{
    public class CourseRecommendationsController : Controller
    {
        private ASPSEntities db = new ASPSEntities();

        // GET: CourseRecommendations
        [Authorize(Roles = "Faculty")]
        public ActionResult Index()
        {
            var courseRecommendations = db.CourseRecommendations.Include(c => c.Course).Include(c => c.Faculty).Include(c => c.Student);
            return View(courseRecommendations.ToList());
        }

        // GET: CourseRecommendations/Details/5
        [Authorize(Roles = "Faculty")]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseRecommendation courseRecommendation = db.CourseRecommendations.Find(id);
            if (courseRecommendation == null)
            {
                return HttpNotFound();
            }
            return View(courseRecommendation);
        }

        // GET: CourseRecommendations/Create
        [Authorize(Roles = "Faculty")]
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseCode");
            ViewBag.FacultyID = new SelectList(db.Faculties, "FacultyID", "FacultyEmail");
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentEmail");
            return View();
        }

        // POST: CourseRecommendations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Faculty")]
        public ActionResult Create([Bind(Include = "ContentID,FacultyID,StudentID,CourseID,CourseRating")] CourseRecommendation courseRecommendation)
        {
            if (ModelState.IsValid)
            {
                db.CourseRecommendations.Add(courseRecommendation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseCode", courseRecommendation.CourseID);
            ViewBag.FacultyID = new SelectList(db.Faculties, "FacultyID", "FacultyEmail", courseRecommendation.FacultyID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentEmail", courseRecommendation.StudentID);
            return View(courseRecommendation);
        }

        // GET: CourseRecommendations/Edit/5
        [Authorize(Roles = "Faculty")]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseRecommendation courseRecommendation = db.CourseRecommendations.Find(id);
            if (courseRecommendation == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseCode", courseRecommendation.CourseID);
            ViewBag.FacultyID = new SelectList(db.Faculties, "FacultyID", "FacultyEmail", courseRecommendation.FacultyID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentEmail", courseRecommendation.StudentID);
            return View(courseRecommendation);
        }

        // POST: CourseRecommendations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Faculty")]
        public ActionResult Edit([Bind(Include = "ContentID,FacultyID,StudentID,CourseID,CourseRating")] CourseRecommendation courseRecommendation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courseRecommendation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseCode", courseRecommendation.CourseID);
            ViewBag.FacultyID = new SelectList(db.Faculties, "FacultyID", "FacultyEmail", courseRecommendation.FacultyID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentEmail", courseRecommendation.StudentID);
            return View(courseRecommendation);
        }

        // GET: CourseRecommendations/Delete/5
        [Authorize(Roles = "Faculty")]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseRecommendation courseRecommendation = db.CourseRecommendations.Find(id);
            if (courseRecommendation == null)
            {
                return HttpNotFound();
            }
            return View(courseRecommendation);
        }

        // POST: CourseRecommendations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Faculty")]
        public ActionResult DeleteConfirmed(long id)
        {
            CourseRecommendation courseRecommendation = db.CourseRecommendations.Find(id);
            db.CourseRecommendations.Remove(courseRecommendation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

last spl2/ASPSWebApp/Controllers/FacultyProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASPSDAL;
using ASPSWebApp.BusinessCode;

namespace ASPSWebApp.Controllers
{
    public class FacultyProfileController : Controller
    {
        private FacultyRepository facultyRepository = new FacultyRepository();
        Faculty _faculty = (Faculty)System.Web.HttpContext.Current.Session["Faculty"];
        // GET: FacultyProfile
        [Authorize(Roles = "Faculty")]
        public ActionResult Index()
        {
            _faculty = facultyRepository.GetFacultyByEmail(_faculty.FacultyEmail);
            return View(_faculty);
        }

        // GET: FacultyProfile/Edit/5
        [Authorize(Roles = "Faculty")]
        public ActionResult Edit()
        {
            if (this._faculty.FacultyEmail == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty currentFaculty = facultyRepository.GetFacultyByEmail(_faculty.FacultyEmail);
            if (currentFaculty == null)
            {
                return HttpNotFound();
            }
            return View(_faculty);
        }

        // POST: FacultyProfile/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Faculty")]
        public ActionResult Edit([Bind(Include = "FacultyID,FacultyEmail,Name,Password,Address,BloodGroup,Gender,Religion,MobileNumber,Designation")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                facultyRepository.EditFaculty(faculty);
                return RedirectToAction("Index");
            }
            return View(faculty);
        }

        [Authorize(Roles = "Faculty")]
        public ActionResult VisitStudentProfile()
        {
            return View(new StudentRepository().StudentsList());
        }

        //Get
        [Authorize(Roles = "Faculty")]
        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Faculty")]
        public ActionResult ChangePassword(string newPassword, string confirmPassword)
        {
            Password password = new Password();
            if (password.ComparePassword(newPassword, confirmPassword))
            {
                Faculty temp = facultyRepository.GetFacultyByEmail(_faculty.FacultyEmail);
                temp.Password = newPassword;
                facultyRepository.EditFaculty(temp);
            }
            return RedirectToAction("Index");
        }
    }
}

last spl2/ASPSWebApp/Views/CourseRecommendations/Create.cshtml
@using ASPSDAL
@model ASPSDAL.CourseRecommendation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @{
                    if ((Session["Faculty"]) != null)
                    {
                        <li>@Html.ActionLink(((Faculty) Session["Faculty"]).Name, "Index", "FacultyProfile")</li>
                    }
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Activity<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink("Edit Basic Information", "Edit", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Change Password", "ChangePassword", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Visit Student Profile", "VisitStudentProfile", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Recommend Student", "Index", "CourseRecommendations")</li>
                </ul>
                <li>@Html.ActionLink("Sign Out", "SignOut", "SignIn")</li>
            </ul>
        </div>
    </div>
</div>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CourseRecommendation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FacultyID, "FacultyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FacultyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FacultyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseRating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseRating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseRating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

last spl2/ASPSWebApp/Views/CourseRecommendations/Delete.cshtml
@using ASPSDAL
@model ASPSDAL.CourseRecommendation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @{
                    if ((Session["Faculty"]) != null)
                    {
                        <li>@Html.ActionLink(((Faculty) Session["Faculty"]).Name, "Index", "FacultyProfile")</li>
                    }
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Activity<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink("Edit Basic Information", "Edit", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Change Password", "ChangePassword", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Visit Student Profile", "VisitStudentProfile", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Recommend Student", "Index", "CourseRecommendations")</li>
                </ul>
                <li>@Html.ActionLink("Sign Out", "SignOut", "SignIn")</li>
            </ul>
        </div>
    </div>
</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CourseRecommendation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseRating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Faculty.FacultyEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Faculty.FacultyEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.StudentEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.StudentEmail)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

last spl2/ASPSWebApp/Views/CourseRecommendations/Details.cshtml
@using ASPSDAL
@model ASPSDAL.CourseRecommendation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @{
                    if ((Session["Faculty"]) != null)
                    {
                        <li>@Html.ActionLink(((Faculty) Session["Faculty"]).Name, "Index", "FacultyProfile")</li>
                    }
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Activity<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink("Edit Basic Information", "Edit", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Change Password", "ChangePassword", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Visit Student Profile", "VisitStudentProfile", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Recommend Student", "Index", "CourseRecommendations")</li>
                </ul>
                <li>@Html.ActionLink("Sign Out", "SignOut", "SignIn")</li>
            </ul>
        </div>
    </div>
</div>

<div>
    <h4>CourseRecommendation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseRating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Faculty.FacultyEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Faculty.FacultyEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.StudentEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.StudentEmail)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ContentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

last spl2/ASPSWebApp/Views/CourseRecommendations/Edit.cshtml
@using ASPSDAL
@model ASPSDAL.CourseRecommendation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @{
                    if ((Session["Faculty"]) != null)
                    {
                        <li>@Html.ActionLink(((Faculty)Session["Faculty"]).Name, "Index", "FacultyProfile")</li>
                    }
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Activity<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Edit Basic Information", "Edit", "FacultyProfile")</li>
                        <li>@Html.ActionLink("Change Password", "ChangePassword", "FacultyProfile")</li>
                        <li>@Html.ActionLink("Visit Student Profile", "VisitStudentProfile", "FacultyProfile")</li>
                        <li>@Html.ActionLink("Recommend Student", "Index", "CourseRecommendations")</li>
                    </ul>
                <li>@Html.ActionLink("Sign Out", "SignOut", "SignIn")</li>
            </ul>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CourseRecommendation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ContentID)

        <div class="form-group">
            @Html.LabelFor(model => model.FacultyID, "FacultyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FacultyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FacultyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseRating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseRating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseRating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

last spl2/ASPSWebApp/Views/CourseRecommendations/Index.cshtml
@using ASPSDAL
@model IEnumerable<ASPSDAL.CourseRecommendation>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @{
                    if ((Session["Faculty"]) != null)
                    {
                        <li>@Html.ActionLink(((Faculty) Session["Faculty"]).Name, "Index", "FacultyProfile")</li>
                    }
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Activity<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink("Edit Basic Information", "Edit", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Change Password", "ChangePassword", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Visit Student Profile", "VisitStudentProfile", "FacultyProfile")</li>
                    <li>@Html.ActionLink("Recommend Student", "Index", "CourseRecommendations")</li>
                </ul>
                <li>@Html.ActionLink("Sign Out", "SignOut", "SignIn")</li>
            </ul>
        </div>
    </div>
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Faculty.FacultyEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.StudentEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseRating)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Faculty.FacultyEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Student.StudentEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course.CourseCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CourseRating)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ContentID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ContentID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ContentID })
        </td>
    </tr>
}

</table>