Final SPL2/ASPS/ASPSWebApp/Controllers/FacultyProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPSWebApp.Controllers
{
    public class FacultyProfileController : Controller
    {
        // GET: FacultyProfile
        public ActionResult Index()
        {
            return View();
        }

        /*public ActionResult Recommend()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Recommend()
        {
            return View();
        }*/

        public ActionResult VisitStudent()
        {
            return View();
        }
    }
}

Final SPL2/ASPS/ASPSWebApp/Controllers/ResultsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASPSDataModel;

namespace ASPSWebApp.Controllers
{
    public class ResultsController : Controller
    {
        private ASPSEntities db = new ASPSEntities();

        // GET: Results
        public ActionResult Index()
        {
            var results = db.Results.Include(r => r.Course).Include(r => r.Student);
            return View(results.ToList());
        }

        // GET: Results/Details/5
        public ActionResult Details(string id)
        {
            //string email = ((Student)Session["Student"])
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // GET: Results/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName");
            ViewBag.StudentEmail = new SelectList(db.Students, "StudentEmail", "StudentEmail");
            return View();
        }

        // POST: Results/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentEmail,CourseID,CourseGrade,CoursePoint,CourseNumber")] Result result)
        {
            ResultRepository resultRepository = new ResultRepository();
            if (resultRepository.ValidResult(result.StudentEmail, result.CourseID))
            {
                Result currentResult = resultRepository.FindResult(result);
                if (currentResult == null)
                {
                    db.Results.Add(result);
                    db.SaveChanges();
                }
                else
                {
                    ViewBag.Message = "This course already added to student";
                }

                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName", result.CourseID);
            ViewBag.StudentEmail = new SelectList(db.Students, "StudentEmail", "Name", result.StudentEmail);
            return View(result);
        }

        // GET: Results/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName", result.CourseID);
            ViewBag.StudentEmail = new SelectList(db.Students, "StudentEmail", "Name", result.StudentEmail);
            return View(result);
        }

        // POST: Results/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentEmail,CourseID,CourseGrade,CoursePoint,CourseNumber")] Result result)
        {
            if (ModelState.IsValid)
            {
                db.Entry(result).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName", result.CourseID);
            ViewBag.StudentEmail = new SelectList(db.Students, "StudentEmail", "Name", result.StudentEmail);
            return View(result);
        }

        // GET: Results/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // POST: Results/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Result result = db.Results.Find(id);
            db.Results.Remove(result);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Final SPL2/ASPS/ASPSWebApp/Views/FacultyProfile/Index.cshtml
@using ASPSDataModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="container">Index</h2>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink(((Faculty)Session["Faculty"]).Name, "Index", "FacultyProfile")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @*<li><a href="@Url.Action("Index", "Search")"><span class="glyphicon glyphicon-search"></span>Search</a></li>*@
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Activity<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Recommend Student", "Index", "Results")</li>
                        <li>@Html.ActionLink("Visit Student", "Index", "Results")</li>
                    </ul>
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-log-out"></span>SignOut</a></li>
            </ul>
        </div>
    </div>
</div>

Final SPL2/ASPS/ASPSWebApp/Views/FacultyProfile/Recommend.cshtml
@{
    ViewBag.Title = "Recommend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Recommend</h2>

Final SPL2/ASPS/ASPSWebApp/Views/FacultyProfile/VisitStudent.cshtml
@using ASPSDataModel

@{
    ViewBag.Title = "VisitStudent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>VisitStudent</h2>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink(((Faculty)Session["Faculty"]).Name, "Index", "FacultyProfile")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @*<li><a href="@Url.Action("Index", "Search")"><span class="glyphicon glyphicon-search"></span>Search</a></li>*@
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Activity<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Recommend Student", "Index", "Results")</li>
                        <li>@Html.ActionLink("Visit Student", "Index", "Results")</li>
                    </ul>
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-log-out"></span>SignOut</a></li>
            </ul>
        </div>
    </div>
</div>


<div class="container">
    @{

        StudentRepository studentRepository = new StudentRepository();
        <h3>Students</h3>
        foreach (var student in studentRepository.StudentsList())
        {
            <hr />
            <div>
                <a href="#">@student.Name</a>
                <p>@student.StudentEmail</p>
            </div>
        }

    }
</div>