last spl2/ASPSWebApp/Controllers/StudentProfileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ASPSDAL;
using ASPSWebApp.BusinessCode;

namespace ASPSWebApp.Controllers
{
    public class StudentProfileController : Controller
    {
        private StudentRepository studentRepository = new StudentRepository();
        private Student _student = (Student) System.Web.HttpContext.Current.Session["Student"];

        // GET: StudentProfile
        [Authorize(Roles = "Student")]
        public ActionResult Index()
        {    
            _student = studentRepository.GetStudentByEmail(_student.StudentEmail);
            return View(_student);
        }

        // GET: StudentProfile/Edit/5
        [Authorize(Roles = "Student")]
        public ActionResult Edit()
        {
            if (this._student.StudentEmail == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student currentStudent = studentRepository.GetStudentByEmail(_student.StudentEmail);
            if (_student == null)
            {
                return HttpNotFound();
            }
            return View(_student);
        }

        // POST: StudentProfile/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Student")]
        public ActionResult Edit([Bind(Include = "StudentID,StudentEmail,Name,Password,BloodGroup,Address,Religion,Gender,Roll,RegistrationNumber,Result,MobileNumber")] Student student)
        {
            if (ModelState.IsValid)
            {
                studentRepository.EditStudent(student);
                return RedirectToAction("Index");
            }
            return View(student);
        }
        //Get
        [Authorize(Roles = "Student")]
        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Student")]
        public ActionResult ChangePassword(string newPassword, string confirmPassword)
        {
            Password password = new Password();
            if (password.ComparePassword(newPassword, confirmPassword))
            {
                Student temp = studentRepository.GetStudentByEmail(_student.StudentEmail);
                temp.Password = newPassword;
                studentRepository.EditStudent(temp);
            }
            return RedirectToAction("Index");
        }
    }
}

last spl2/ASPSWebApp/Views/StudentProfile/ChangePassword.cshtml
@using ASPSDAL
@model ASPSDAL.Student

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @{
                    if((Session["Student"]) != null)
                        {
                            <li>@Html.ActionLink(((Student)Session["Student"]).Name, "Index", "StudentProfile")</li>
                        }
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Activity<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink("Edit Basic Information", "Edit", "StudentProfile")</li>
                    <li>@Html.ActionLink("Change Password", "ChangePassword", "StudentProfile")</li>
                    <li>@Html.ActionLink("Add Content", "Index", "Contents")<li/>
                </ul>
                <li>@Html.ActionLink("Sign Out", "SignOut", "SignIn")</li>
            </ul>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Current Password", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                <input type="password" class="form-control" placeholder="current password" id="current_pass" name="currentPassword"/>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("New Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="password" class="form-control" placeholder="new password" id="new_pass" name="newPassword" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Confirm Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="password" class="form-control" placeholder="confirm password" id="confirm_pass" name="confirmPassword"/>
                <span id="confirmMessage" class="confirmMessage"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" id="save" onclick="myCheck()"/>
            </div>
        </div>
    </div>
}
@{
    var prevPass = ((Student)Session["Student"]).Password;
    <script type="text/javascript">
        var message = document.getElementById("confirmMessage");
        function myCheck()
        {
            //alert("Done");

            if (document.getElementById("current_pass").compare(prevPass) && document.getElementById("new_pass").toString().compare(document.getElementById("confirm_pass"))) {
                message.innerHTML = "password match!! password changed successful";
                alert("Password changed successfully");
            } else
                message.innerHTML = "Password didn't match & password not updated";
        }
    </script>
}

@section Scripts {
    
    @Scripts.Render("~/bundles/jqueryval")
}

last spl2/ASPSWebApp/Views/StudentProfile/Edit.cshtml
@using ASPSDAL
@model ASPSDAL.Student

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @{
                    if ((Session["Student"]) != null)
                    {
                        <li>@Html.ActionLink(((Student)Session["Student"]).Name, "Index", "StudentProfile")</li>
                    }
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Activity<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink("Edit Basic Information", "Edit", "StudentProfile")</li>
                    <li>@Html.ActionLink("Change Password", "ChangePassword", "StudentProfile")</li>
                    <li>@Html.ActionLink("Add Content", "Index", "Contents")</li>
                </ul>
                <li>@Html.ActionLink("Sign Out", "SignOut", "SignIn")</li>
            </ul>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentID)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BloodGroup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BloodGroup, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BloodGroup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Religion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Religion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Religion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Roll, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Roll, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Roll, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Result, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Result, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Result, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

last spl2/ASPSWebApp/Views/StudentProfile/Index.cshtml
@using ASPSDAL
@model ASPSDAL.Student

<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
                    if ((Session["Student"]) != null)
                    {
                <li>@Html.ActionLink(((Student)Session["Student"]).Name, "Index", "StudentProfile")</li>
                    }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Activity<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Edit Basic Information", "Edit", "StudentProfile")</li>
                            <li>@Html.ActionLink("Change Password", "ChangePassword", "StudentProfile")</li>
                            <li>@Html.ActionLink("Add Content", "Index", "Contents")</li>
                        </ul>
                    <li>@Html.ActionLink("Sign Out", "SignOut", "SignIn")</li>
                </ul>
            </div>
        </div>
    </div>

<div class="container">
        <h4>Student</h4>
        @*<div>
            <img src="~/Content/images/default-person.png" width="200" height="200" />
        </div>
        <div>
            <input type="button" class="btn btn-default" value="Upload" name="imgUpload" />
        </div>*@

        <h3>Basic Information</h3>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                Name
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                Email
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StudentEmail)
            </dd>

            <dt>
                Blood Group
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BloodGroup)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Religion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Religion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MobileNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MobileNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>
        </dl>
        <hr />
    </div>
<div class="container">
    <h3>Academic Information</h3>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Roll)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Roll)
        </dd>

        <dt>
            Registration Number
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Result)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Result)
        </dd>
    </dl>
    <hr/>
</div>
<div class="container">
    <h3>Content Information</h3>
    <hr/>
    @{
        ContentRepository contentRepository = new ContentRepository();

        List<Content> contents = contentRepository.GetContentsByStudentId(Model.StudentID);
        foreach (var content in contents)
        {
            <dl class="dl-horizontal">
                <dt>
                    Type
                </dt>
                <dd>
                    @content.ContentType
                </dd>
                <dt>
                    File Name
                </dt>
                <dd>
                    @content.ContentPath
                </dd>
                <dt>
                    Description
                </dt>
                <dd>
                    @content.ContentDescription
                </dd>
            </dl>
            <hr />
        }
    }
    
</div>